test_that("parentChain shows in 'not on CRAN' message for deps of a local package", {
  # Integration test for the parentChain feature.
  #
  # Strategy: create a minimal file:// CRAN-like repo containing dummypkgwithpryr
  # (which lists Imports: pryr).  When pkgDep() queries available.packages() it finds
  # dummypkgwithpryr there, reads Imports: pryr from the PACKAGES index, then recurses
  # for pryr.  pryr is archived on real CRAN, so pkgDepCRAN prints:
  #   "pryr (required by: dummypkgwithpryr) not on CRAN; checking CRAN archives ..."
  #
  # Using a file:// repo avoids relying on cache-scanning (identifyLocalFiles), which
  # has platform-specific behaviour, and keeps the test self-contained except for the
  # final CRAN-archive lookup for pryr itself.

  skip_if_offline2()
  setupInitial <- setupTest()

  td <- Require:::tempdir2("test_parentChain_integration")
  on.exit(unlink(td, recursive = TRUE), add = TRUE)

  pkgname <- "dummypkgwithpryr"
  ver     <- "1.0"
  tarname <- paste0(pkgname, "_", ver, ".tar.gz")

  # ── 1. Build dummypkgwithpryr_1.0.tar.gz ──────────────────────────────────────
  srcDir <- file.path(td, "src")
  pkgDir <- file.path(srcDir, pkgname)
  dir.create(pkgDir, recursive = TRUE)
  writeLines(c(
    paste0("Package: ", pkgname),
    paste0("Version: ", ver),
    "Title: Dummy package for testing parentChain messaging",
    "Description: Imports pryr to exercise the archived-CRAN parentChain message.",
    "Imports: pryr",
    "License: GPL-3"
  ), file.path(pkgDir, "DESCRIPTION"))

  tarfile <- file.path(td, tarname)
  withr::with_dir(srcDir,
    utils::tar(tarfile, files = pkgname, compression = "gzip", tar = "internal"))

  # ── 2. Build a minimal file:// CRAN-like repo ─────────────────────────────────
  # Layout:  repoDir/src/contrib/PACKAGES  (generated by tools::write_PACKAGES)
  #          repoDir/src/contrib/dummypkgwithpryr_1.0.tar.gz
  repoDir  <- file.path(td, "repo")
  contribs <- file.path(repoDir, "src", "contrib")
  dir.create(contribs, recursive = TRUE)
  file.copy(tarfile, file.path(contribs, tarname))

  # write_PACKAGES reads the tarball's DESCRIPTION to build the index
  tools::write_PACKAGES(contribs, type = "source", verbose = FALSE)

  fileRepo <- paste0("file:///", normalizePath(repoDir, winslash = "/", mustWork = FALSE))

  # ── 3. Run pkgDep with the file repo first, then CRAN for pryr ────────────────
  # repos order: file repo (finds dummypkgwithpryr) then CRAN (finds pryr is archived)
  repos <- c(fileRepo, "https://cloud.r-project.org")

  msgs <- character(0)
  withCallingHandlers(
    tryCatch(
      pkgDep(pkgname,
             repos     = repos,
             type      = "source",  # file repo only has src/contrib; binary lookup would find nothing
             verbose   = 1,
             recursive = TRUE,
             purge     = TRUE),   # purge so the file repo is queried fresh
      error = function(e) NULL    # swallow downstream errors after the message fires
    ),
    message = function(m) {
      msgs <<- c(msgs, conditionMessage(m))
      invokeRestart("muffleMessage")
    }
  )

  # ── 4. Assert the dependency chain appears in the "not on CRAN" message ────────
  not_on_cran_msgs <- msgs[grepl("not on CRAN", msgs, fixed = TRUE)]
  # Use word-boundary so "dummypkgwithpryr" (contains "pryr") is not matched
  pryr_not_on_cran <- not_on_cran_msgs[grepl("\\bpryr\\b", not_on_cran_msgs)]

  testthat::expect_true(
    length(pryr_not_on_cran) > 0,
    info = paste("Expected a 'pryr ... not on CRAN' message. Messages captured:\n",
                 paste(msgs, collapse = "\n"))
  )
  testthat::expect_true(
    any(grepl(paste0("required by: ", pkgname), pryr_not_on_cran, fixed = TRUE)),
    info = paste0("Expected '(required by: ", pkgname, ")' in the pryr 'not on CRAN' ",
                  "message. Got:\n", paste(pryr_not_on_cran, collapse = "\n"))
  )
})
